apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: {{ include "devworkspace-operator.name" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
