apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: {{ include "devworkspace-operator.name" . }}-metrics
  
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
