apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: {{ include "devworkspace-operator.name" . }}-leader-election-rolebinding
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "devworkspace-operator.name" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "devworkspace-operator.serviceAccountName" . }}
  
