apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: {{ include "devworkspace-operator.name" . }}-edit-workspaces
rules:
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  - devworkspacetemplates
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings
  - devworkspaceoperatorconfigs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
