apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: devworkspace-controller-serving-cert
  
spec:
  dnsNames:
  - devworkspace-webhookserver.devworkspace-controller.svc
  - devworkspace-webhookserver.devworkspace-controller.svc.cluster.local
  - devworkspace-controller-manager-service.devworkspace-controller.svc
  - devworkspace-controller-manager-service.devworkspace-controller.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: devworkspace-controller-selfsigned-issuer
  secretName: devworkspace-operator-webhook-cert
