apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: devworkspace-controller-selfsigned-issuer
  
spec:
  selfSigned: {}
