apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: {{ include "devworkspace-operator.name" . }}-selfsigned-issuer
  
spec:
  selfSigned: {}
