apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: devworkspace-controller-manager-service
  
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: conversion
  selector:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
