apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "devworkspace-operator.labels" . | nindent 4 }}
  name: devworkspace-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devworkspace-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "devworkspace-operator.serviceAccountName" .}}
  namespace: {{ include "devworkspace-operator.namespace" . }}